services:
  health-tracker:
    build: .
    env_file: ./.env
    command: uvicorn api.sentient_roma_api:app --host 0.0.0.0 --port 8000
    volumes:
      - ./data:/app/data
      - ./roma_config:/app/roma_config:ro
    ports:
      - "8000:8000"
    restart: unless-stopped

  roma:
    build:
      context: ./external/ROMA
      dockerfile: docker/Dockerfile
    env_file: ./.env
    volumes:
      - ./sentient.yaml:/app/sentient.yaml:ro
      - ./roma_config:/app/roma_config:ro
      - ./external/ROMA/project_results:/app/project_results
      - ./external/ROMA/emergency_backups:/app/emergency_backups
    ports:
      - "5000:5000"
    restart: unless-stopped
